/* Gentle rotating phrases shown in the header's idle text (see HEADER_IDLE_PHRASES usage in
   index.html) — cycles a random one every ~10s while no reward-scene image is showing.
   Edit freely; add or remove lines as you like. ru/en don't need to match 1:1 in count, but
   keep both lists non-empty. */

var HEADER_IDLE_PHRASES = {
  ru: [
    "Мышка сказала, что сегодня у неё выходной.",
    "Фокусируйся на главном.",
    "Один шаг за раз — этого достаточно.",
    "Сегодня уже неплохой день.",
    "Если мысли запутались, представь, что это просто клубок.",
    "Я считаю даже самые маленькие победы. Особенно маленькие.",
    "Ты сильнее, чем думаешь.",
    "Пойду проверю свою миску. А ты проверь свой стаканчик с водой.",
    "Отдых — часть плана, а не отступление от него.",
    "Всё получится, если не спешить.",
    "Твой темп — правильный темп.",
    "Сделал что-то — уже молодец.",
    "Солнечный лучик официально занят мной.",
    "Немного магии в каждом обычном дне.",
    "Я рядом. Если что — помурлычу.",
    "Похоже, сегодня отличный день, чтобы никуда не торопиться.",
    "Сегодня можно не быть идеальным. Я разрешаю.",
    "Даже маленькие шаги ведут к цели.",
    "Заботься о себе так же, как о делах.",
    "Хороший план начинается с одного пункта.",
    "Если за окном дождь, можно быть чуточку медленнее.",
    "Ты уже сделал больше, чем кажется.",
    "Проговорить мысль вслух — тоже прогресс.",
    "Я никогда не сравниваю людей. Разве что по умению чесать котиков.",
    "Не переживай. Креветки тоже не всё успевают.",
    "Всё по порядку — и всё получится.",
    "Забота о себе имеет значение.",
    "Маленький шаг — тоже шаг вперёд.",
    "Я вообще иногда просто лежу. И знаешь... тоже неплохо получается.",
    "Сегодня снилась очень большая рыба. Почти настоящая.",
    "Не забывай хвалить себя.",
    "Я проверил все кресла. Это было очень ответственно."
  ],
  en: [
    "The mouse said she's taking the day off.",
    "Focus on what matters most.",
    "One step at a time is enough.",
    "Today is already a good day.",
    "If your thoughts get tangled, just picture it as a ball of yarn.",
    "I count even the smallest wins. Especially the small ones.",
    "You're stronger than you think.",
    "I'm off to check my bowl. You go check your water glass.",
    "Rest is part of the plan, not a step back.",
    "It'll all work out if you don't rush.",
    "Your pace is the right pace.",
    "You did something — that's already great.",
    "This sunbeam is officially occupied by me.",
    "There's a little magic in every ordinary day.",
    "I'm right here. If you need it, I'll purr.",
    "Seems like today's a great day to not rush anywhere.",
    "You don't have to be perfect today. I give you permission.",
    "Even tiny steps lead somewhere.",
    "Take care of yourself the way you take care of tasks.",
    "A good plan starts with just one item.",
    "If it's raining outside, it's okay to slow down a little.",
    "You've already done more than it feels like.",
    "Saying a thought out loud counts as progress too.",
    "I never compare people. Except by how well they scratch cats.",
    "Don't worry. Even shrimp don't get everything done.",
    "One thing at a time — it'll all come together.",
    "Taking care of yourself matters.",
    "A small step is still a step forward.",
    "Sometimes I just lie around. And you know... it works out pretty well.",
    "I dreamed of a really big fish last night. Almost real.",
    "Don't forget to praise yourself.",
    "I checked all the armchairs. It was a very responsible job."
  ]
};
