/* Reward data for the two treasure collections shown in the "Сокровища" tab.
   This file only describes WHAT each reward is — id, source image filename, title and
   description. It knows nothing about file paths or how it's rendered; index.html turns
   `filename` into a real <img src> by joining it with "collections/<collectionKey>/".

   filename must exactly match a real file inside collections/items/ or collections/food/ —
   these are pulled straight from the actual folders, not invented names.

   title/description are { ru, en } pairs — index.html picks the right one for the active
   language at render time (see localizedField in renderCollection). Both must stay filled in;
   ru is what actually ships the voice/jokes, en is a same-spirit translation of it. */

var REWARDS_DATA = {
  items: [
    { id: "items-1",  filename: "1 (1).png",
      title: { ru: "Кораблик в бутылке", en: "Ship in a Bottle" },
      description: { ru: "Я до сих пор ломаю голову, как его туда засунули. Скорее всего, корабль там просто вырос.", en: "I still can't figure out how it got in there. The ship probably just grew inside." } },
    { id: "items-2",  filename: "1 (2).png",
      title: { ru: "Швабра...с вилкой?", en: "Mop... with a Fork?" },
      description: { ru: "Два в одном! И прибраться, и дотянуться до вкусного", en: "Two in one! Clean the floor and reach the snacks." } },
    { id: "items-3",  filename: "1 (3).png",
      title: { ru: "Чайник с отлетевшей крышечкой", en: "Teapot with a Missing Lid" },
      description: { ru: "Все мы немного этот чайник", en: "We're all a little bit this teapot." } },
    { id: "items-4",  filename: "1 (4).png",
      title: { ru: "Витражная лампа", en: "Stained-Glass Lamp" },
      description: { ru: "От нее такой уютный свет по вечерам... Разноцветные пятнышки подходят к моей шубке", en: "It gives off such cozy light in the evenings... The colorful spots match my fur perfectly." } },
    { id: "items-5",  filename: "1 (5).png",
      title: { ru: "Усятница", en: "Whisker Keeper" },
      description: { ru: "Не, ну ты же будешь хранить мои усики?", en: "You will keep my little whiskers safe, right?" } },
    { id: "items-6",  filename: "1 (6).png",
      title: { ru: "Шорты с хвостиком", en: "Shorts with a Little Tail" },
      description: { ru: "Вдруг тебе тоже хочется побыть немного мистером Лапкинсом", en: "In case you ever want to feel like Mr. Lapkins too." } },
    { id: "items-7",  filename: "1 (7).png",
      title: { ru: "Зуб зебры", en: "Zebra Tooth" },
      description: { ru: "Был в зоопарке. Хотел купить тебе сувенир... но этот лежал бесплатно.", en: "Went to the zoo. Wanted to buy you a souvenir... but this one was just lying around for free." } },
    { id: "items-8",  filename: "1 (8).png",
      title: { ru: "Уютная чашечка", en: "Cozy Little Cup" },
      description: { ru: "У меня в нее мордочка не помещается, так что держи, пей свой кофе", en: "My face doesn't fit in it, so here, go drink your coffee." } },
    { id: "items-9",  filename: "1 (9).png",
      title: { ru: "Уточка-лепрекон", en: "Leprechaun Duck" },
      description: { ru: "Это инвестиция: золота нет, зато усы роскошные", en: "Think of it as an investment: no gold, but the mustache is magnificent." } },
    { id: "items-10", filename: "1 (10).png",
      title: { ru: "Синяя изолента", en: "Blue Duct Tape" },
      description: { ru: "У тебя есть изолента? Нет? Держи изоленту", en: "Got any duct tape? No? Here, have some duct tape." } },
    { id: "items-11", filename: "1 (11).png",
      title: { ru: "Рыба-сабля", en: "Sword Fish" },
      description: { ru: "Тайное оружие: грозное, но подозрительно пахнет минтаем", en: "A secret weapon: fearsome, but suspiciously smells like pollock." } },
    { id: "items-12", filename: "1 (12).png",
      title: { ru: "Резиновые сапоги", en: "Rubber Boots" },
      description: { ru: "Принёс их для твоих лапок, но искренне не понимаю, почему у тебя их всего две, а не четыре.", en: "Brought these for your paws, but I honestly don't understand why you only have two and not four." } },
    { id: "items-13", filename: "1 (13).png",
      title: { ru: "Плюшевое авокадо", en: "Plush Avocado" },
      description: { ru: "Я спал на нем, когда был котенком, но теперь у меня сползает с него попа", en: "I used to sleep on it as a kitten, but now my butt slides right off." } },
    { id: "items-14", filename: "1 (14).png",
      title: { ru: "Садовая фигурка гном-сурикат", en: "Garden Gnome-Meerkat Figurine" },
      description: { ru: "Даже если нет сада - сурикат отлично устроится на подоконнике", en: "Even without a garden, a meerkat settles in just fine on a windowsill." } },
    { id: "items-15", filename: "1 (15).png",
      title: { ru: "Крем для лапок", en: "Paw Cream" },
      description: { ru: "Всё работаешь и работаешь, все лапки стёр. На, вот, намажь.", en: "You work and work and work, you've worn your paws right down. Here, put some of this on." } },
    { id: "items-16", filename: "1 (16).png",
      title: { ru: "Трубка с головой дракона", en: "Dragon-Head Bubble Pipe" },
      description: { ru: "Из нее выходят мыльные пузыри, знаешь как здорово их лопать лапками?", en: "It blows soap bubbles — you have no idea how fun they are to pop with paws." } },
    { id: "items-17", filename: "1 (17).png",
      title: { ru: "Шляпа волшебника", en: "Wizard Hat" },
      description: { ru: "Главное волшебство тут - это ты. А шляпа - спасает от дождя, она непромокаемая", en: "The real magic here is you. The hat's just waterproof, so it keeps the rain off." } },
    { id: "items-18", filename: "1 (18).png",
      title: { ru: "Надувной дельфин", en: "Inflatable Dolphin" },
      description: { ru: "Если сильно захотеть, даже дельфин может летать", en: "If you want it badly enough, even a dolphin can fly." } },
    { id: "items-19", filename: "1 (19).png",
      title: { ru: "Куртка с парашютом", en: "Jacket with a Parachute" },
      description: { ru: "Уверяю: если дела полетят в тартарары, парашют раскроется автоматически. Но это не точно", en: "I assure you: if things go straight to hell, the parachute deploys automatically. Probably." } },
    { id: "items-20", filename: "1 (20).png",
      title: { ru: "Рюкзак - морская звезда", en: "Starfish Backpack" },
      description: { ru: "Прозрачный намёк: сложи туда все дела и иди просто лежать звездой", en: "A not-so-subtle hint: pack all your to-dos in there and go lie around like a starfish." } },
    { id: "items-21", filename: "1 (21).png",
      title: { ru: "Перо", en: "Feather" },
      description: { ru: "Я долго нёс это перо. Было очень сложно не начать с ним играть", en: "I carried this feather a long way. It was very hard not to start playing with it." } },
    { id: "items-22", filename: "1 (22).png",
      title: { ru: "Три разных носка", en: "Three Odd Socks" },
      description: { ru: "Один всегда теряется. А разные - на удачу", en: "One always goes missing. Mismatched ones are for good luck." } },
    { id: "items-23", filename: "1 (23).png",
      title: { ru: "Подушка", en: "Pillow" },
      description: { ru: "Это не просто подушка, ее идеально зажимать между лап во сне", en: "This isn't just a pillow — it's perfect for hugging between your paws while you sleep." } },
    { id: "items-24", filename: "1 (24).png",
      title: { ru: "Пингвин - свечка", en: "Penguin Candle" },
      description: { ru: "Пингвин... Гвинпин... Не летает, зато светится", en: "Penguin... Peingun... Doesn't fly, but it does glow." } },
    { id: "items-25", filename: "1 (25).png",
      title: { ru: "Ловец снов", en: "Dreamcatcher" },
      description: { ru: "По ночам у меня тыгыдык, поэтому он будет защишать тебя от плохих снов", en: "I get the zoomies at night, so this will protect you from bad dreams." } },
    { id: "items-26", filename: "1 (26).png",
      title: { ru: "Тазик для омовения лап", en: "Paw-Washing Basin" },
      description: { ru: "Фух... Ещё чуть-чуть — и лапки были бы мокрые", en: "Phew... just a little more and my paws would've gotten wet." } },
    { id: "items-27", filename: "1 (27).png",
      title: { ru: "Шапочка из фольги", en: "Tinfoil Hat" },
      description: { ru: "Не читай новости, а то тебе эта фигня реально понадобится", en: "Don't read the news, or you'll actually need this thing." } }
  ],
  food: [
    { id: "food-1",  filename: "1 (1).png",
      title: { ru: "Сырный единорог", en: "Cheese Unicorn" },
      description: { ru: "Ходят слухи, что дырки в нем от чужих рогов. Но это просто маасдам", en: "Rumor has it the holes are from other unicorns' horns. But really, it's just Maasdam." } },
    { id: "food-2",  filename: "1 (2).png",
      title: { ru: "Шоколадный гвоздь", en: "Chocolate Nail" },
      description: { ru: "В стену его не забьешь, но можно съесть", en: "Can't hammer it into a wall, but you can eat it." } },
    { id: "food-3",  filename: "1 (3).png",
      title: { ru: "Бублик", en: "Bagel" },
      description: { ru: "Я хочу, чтобы ты посмотрел в дырочку: видишь? Твоих проблем там нет", en: "I want you to look through the hole: see? None of your problems are in there." } },
    { id: "food-4",  filename: "1 (4).png",
      title: { ru: "Улыбчивый хинкали", en: "Smiley Khinkali" },
      description: { ru: "У каждого внутри найдётся немного тепла. У хинкали — ещё и бульон", en: "Everyone's got a little warmth inside. Khinkali also has broth." } },
    { id: "food-5",  filename: "1 (5).png",
      title: { ru: "Ватрушка - космос", en: "Cosmic Vatrushka" },
      description: { ru: "Думаю, если ее съесть, то тебя ждут невероятные приключения", en: "I think if you eat it, incredible adventures await you." } },
    { id: "food-6",  filename: "1 (6).png",
      title: { ru: "Слива - цеппелин", en: "Zeppelin Plum" },
      description: { ru: "Вообще не знаю, что это. Повесь на потолок может?", en: "Honestly no idea what this is. Maybe hang it from the ceiling?" } },
    { id: "food-7",  filename: "1 (7).png",
      title: { ru: "Леденец", en: "Lollipop" },
      description: { ru: "Я долго думал, что он мне напоминает... Потом посмотрел в зеркало.", en: "I thought for a long time what it reminded me of... Then I looked in the mirror." } },
    { id: "food-8",  filename: "1 (8).png",
      title: { ru: "Шоколадная лягушка", en: "Chocolate Frog" },
      description: { ru: "Там внутри еще сюрприз, возможно лягушка поменьше", en: "There's a surprise inside — possibly an even smaller frog." } },
    { id: "food-9",  filename: "1 (9).png",
      title: { ru: "Квадратный арбуз", en: "Square Watermelon" },
      description: { ru: "Мы все можем быть самой странной формы и вида, но внутри всё равно остаёмся сочными и классными", en: "We can all be the strangest shape and look, but inside we're still juicy and great." } },
    { id: "food-10", filename: "1 (10).png",
      title: { ru: "Горшочек меда", en: "Pot of Honey" },
      description: { ru: "Повстречал медведя. Думал уносить лапки, но он оказался плюшевым", en: "Ran into a bear. Was about to make a run for it, but turned out it was a plush one." } },
    { id: "food-11", filename: "1 (11).png",
      title: { ru: "Марципановый лось", en: "Marzipan Moose" },
      description: { ru: "Марципан нравится не всем, но ведь и лосей ты кусаешь не каждый день", en: "Not everyone likes marzipan, but then again, you don't bite a moose every day either." } },
    { id: "food-12", filename: "1 (12).png",
      title: { ru: "Хихикающая груша", en: "Giggling Pear" },
      description: { ru: "Просто пощекочи ее", en: "Just tickle it." } },
    { id: "food-13", filename: "1 (13).png",
      title: { ru: "Торт свечками вниз", en: "Upside-Down Candle Cake" },
      description: { ru: "Никогда не взрослей. храни своего внутреннего ребенка!", en: "Never grow up. Keep your inner child safe!" } },
    { id: "food-14", filename: "1 (14).png",
      title: { ru: "Пончик Сатурна", en: "Saturn Donut" },
      description: { ru: "Я не понимаю, как держится колечко?..", en: "I don't get it, how does the little ring even stay up?.." } },
    { id: "food-15", filename: "1 (15).png",
      title: { ru: "Свежая вода", en: "Fresh Water" },
      description: { ru: "Я уже попробовал. Вода отличная, рекомендую", en: "Already tried it. The water's great, highly recommend." } },
    { id: "food-16", filename: "1 (16).png",
      title: { ru: "Кошачий корм", en: "Cat Food" },
      description: { ru: "Если не будешь есть сушинки, отдай мне.", en: "If you're not gonna eat the kibble, hand it over." } },
    { id: "food-17", filename: "1 (17).png",
      title: { ru: "Молочный коктейль", en: "Milkshake" },
      description: { ru: "С ромашками! Охлаждающе-успокаивающая пенка", en: "With chamomile! A cooling, soothing foam." } },
    { id: "food-18", filename: "1 (18).png",
      title: { ru: "Лавровый лист", en: "Bay Leaf" },
      description: { ru: "Лавровый лист никогда не спрашивает, нужен ли он супу", en: "A bay leaf never asks if the soup actually needs it." } },
    { id: "food-19", filename: "1 (19).png",
      title: { ru: "Горшок с леденцами", en: "Pot of Candy" },
      description: { ru: "Извини, что я уронил горшок с фиалкой вчера, этот вот лучше", en: "Sorry about knocking over the violet pot yesterday — this one's better anyway." } },
    { id: "food-20", filename: "1 (20).png",
      title: { ru: "Кактус-канапе", en: "Cactus Canapé" },
      description: { ru: "А ты знаешь, что кактусы могут быть очень вкусными?", en: "Did you know cacti can actually be quite tasty?" } },
    { id: "food-21", filename: "1 (21).png",
      title: { ru: "Фрикаделька", en: "Meatball" },
      description: { ru: "Можешь съесть, а можешь просто катать по полу", en: "You can eat it, or you can just roll it around the floor." } },
    { id: "food-22", filename: "1 (22).png",
      title: { ru: "Взбитые сливки", en: "Whipped Cream" },
      description: { ru: "Отлично подходит чтобы сделать шапочку на голове. Я уже примерил. Мне идёт", en: "Great for making a little hat on your head. Already tried it myself. Suits me." } },
    { id: "food-23", filename: "1 (23).png",
      title: { ru: "Дуриан", en: "Durian" },
      description: { ru: "Я бы не стал его резать. Вдруг задохнёшься, а у меня лапки...", en: "I wouldn't cut this one open. What if you suffocate — and I've only got paws..." } },
    { id: "food-24", filename: "1 (24).png",
      title: { ru: "Макаронный монстр", en: "Pasta Monster" },
      description: { ru: "Макарошки-макарошки, у них пушистенькие ножки.", en: "Little noodles, little noodles, they've got fuzzy little legs." } },
    { id: "food-25", filename: "1 (25).png",
      title: { ru: "Консервная банка", en: "Tin Can" },
      description: { ru: "Я не знаю, что внутри. Рискнешь открыть?", en: "No idea what's inside. Care to risk opening it?" } },
    { id: "food-26", filename: "1 (26).png",
      title: { ru: "Суп из водорослей", en: "Seaweed Soup" },
      description: { ru: "Я долго на него смотрел. Потом решил, что сначала ты попробуешь", en: "I stared at it for a long time. Then decided you should try it first." } },
    { id: "food-27", filename: "1 (27).png",
      title: { ru: "Мышка", en: "Mouse" },
      description: { ru: "В смысле 'я не ем мышей'?", en: "What do you mean, 'I don't eat mice'?" } }
  ]
};
